Fix installing llvm on Windows

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -24,7 +24,31 @@ jobs:
         if: ${{ startsWith(matrix.OS, 'windows') }}
         shell: pwsh
         run: |
-          Choco-Install -PackageName llvm -ArgumentList "--version=16.0.6", "--allow-downgrade", "--force"
+          $retryCount = 3
+          $retryDelay = 5  # seconds
+
+          function InstallLLVM {
+              Write-Host "Attempting to install LLVM (try $($retryCount + 1 - $global:retryAttempt) of $($retryCount + 1))..."
+              choco install llvm --version=17.0.6 --allow-downgrade --force
+          }
+
+          # Attempt to install LLVM with retries
+          for ($global:retryAttempt = 1; $global:retryAttempt -le $retryCount; $global:retryAttempt++) {
+              try {
+                  InstallLLVM
+                  Write-Host "LLVM installation successful!"
+                  break  # Exit the loop if installation is successful
+              } catch {
+                  Write-Host "Error installing LLVM: $_"
+                  if ($global:retryAttempt -lt $retryCount) {
+                      Write-Host "Retrying in $retryDelay seconds..."
+                      Start-Sleep -Seconds $retryDelay
+                  } else {
+                      Write-Host "Maximum retry attempts reached. Exiting."
+                      exit 1
+                  }
+              }
+          }
           echo "${env:ProgramFiles}\LLVM\bin" | Out-File -FilePath ${env:GITHUB_PATH} -Encoding utf8 -Append
           echo "LLVM_BIN=${env:ProgramFiles}\LLVM\bin" >> ${env:GITHUB_OUTPUT}
 
